var places = [
  {
    name: ("Holsem Coffee"),
    lat: 32.7481701,
    lng: -117.1329807,
    description: "It's all about The Woods latte, made with hazelnut milk and maple syrup bitters. Plus, the clean interior design makes it easy to buckle down and get some work done.",
    search: 'holsem+coffee',
    hasBeer: false,
    hasFood: false,
    hasOutdoor: false,
    hasParking: false,
  },
  {
    name: "Shore Thing Cafe",
    lat: 32.8536838,
    lng: -117.2562501,
    description: "Great for a leisurely work day and an afternoon stroll on La Jolla Shores.",
    search: 'la+jolla+shores',
    hasBeer: false,
    hasFood: false,
    hasOutdoor: false,
    hasParking: true,
  },
  {
    name: "Better Buzz Coffee: Point Loma",
    lat: 32.7262158,
    lng: -117.2303712,
    description: "A small but vibrant coffee shop with great almond milk lattes.",
    search: 'better+buzz+coffee+san+diego',
    hasBeer: false,
    hasFood: false,
    hasOutdoor: true,
    hasParking: true,
  },
  {
    name: "Kettle & Stone",
    lat: 32.7515954,
    lng: -117.1804755,
    description: "This cafe is partially overrun by a hanging garden, making it a tranquil spot for some heavy thinking.",
    search: 'coffee+garden',
    hasBeer: false,
    hasFood: false,
    hasOutdoor: true,
    hasParking: true,
  },
  {
    name: "Krakatoa",
    lat: 32.7174942,
    lng: -117.1427549,
    description: "A massive outdoor patio with plenty of outlets. Delicious peanut butter bars. What's not to love?",
    search: 'krakatoa+san+diego+coffee',
    hasBeer: true,
    hasFood: true,
    hasOutdoor: true,
    hasParking: true,
  },
  {
    name: "Living Room of Point Loma",
    lat: 32.7206271,
    lng: -117.2349288,
    description: "Another outdoor favorite, set in a craftsman home.",
    search: 'living+room+point+loma+coffee',
    hasBeer: false,
    hasFood: false,
    hasOutdoor: true,
    hasParking: true,
  },
  {
    name: "Baba Coffee",
    lat: 33.1619922,
    lng: -117.3530438,
    description: "Grab a craft beer and a melt-in-your-mouth chocolate chip cookie while you work.",
    search: 'beer+coffee',
    hasBeer: true,
    hasBeer: true,
    hasFood: true,
    hasOutdoor: true,
    hasParking: true,
  },
  {
    name: "Starbucks",
    lat: 32.842778,
    lng: -117.2720847,
    description: "This Starbucks is unique because it offers an expansive outdoor patio.",
    search: 'starbucks+la+jolla',
    hasBeer: false,
    hasFood: true,
    hasOutdoor: true,
    hasParking: false,
  },
  {
    name: "Halcyon",
    lat: 32.7102906,
    lng: -117.1538865,
    description: "If you're craving more of an urban feel, head to this East Village coffee shop and sit on their balcony for great city views.",
    search: 'halcyon+east+village',
    hasBeer: true,
    hasFood: true,
    hasOutdoor: true,
    hasParking: false,
  }
];
